fix: virtualization, printf syntax, add: haproxy
 - fix: autorun/swapfile failed outside of Amazon EC2
 - fix: autorun/networking - try to mount filesystems, mountnfs might have failed
 - fix: virtualization detection failure introduced by removing "functions" file
 - fix: cleanup printf parameter syntax
 - add: haproxy support

diff --git a/etc/runit/autorun/swapfile b/etc/runit/autorun/swapfile
--- a/etc/runit/autorun/swapfile
+++ b/etc/runit/autorun/swapfile
@@ -7,24 +7,26 @@
 
 # quit if there is already active swap space
 if [ $(grep -ivc '^Filename' /proc/swaps 2>/dev/null) -ne 0 ]; then
-	printf "Swap is already active.\n"
+	printf 'Swap is already active.\n'
 	exit
 fi
 
 # default swapfile path
 SWAP_PATH=
 [ -s /etc/default/swapfile ] && . /etc/default/swapfile
+[ "$SWAP_PATH" ] || exit
 if [ ! -d "$SWAP_PATH" ]; then
 	# wait for mount to finish after boot
 	sleep 5
 	if [ ! -d "$SWAP_PATH" ]; then
-		printf "Error: swap path %s is not available.\n" "$SWAP_PATH"
+		printf 'Error: swap path %s is not available.\n' "$SWAP_PATH"
 		exit
 	fi
 fi
 
-# make unique swapfile name (from AWS instance name)
+# use unique swapfile name from AWS instance name or hostname
 INSTANCE_ID="$(/usr/local/bin/ec2-metadata --instance-id 2>/dev/null | grep -io '[a-z0-9\-]*$')"
+[ "$INSTANCE_ID" ] || INSTANCE_ID="$(hostname)"
 [ "$INSTANCE_ID" ] || exit
 
 # create new swapfile
@@ -32,20 +34,23 @@ SWAPFILE="$SWAP_PATH/$INSTANCE_ID.swap"
 if [ ! -f "$SWAPFILE" ]; then
 	RAMSIZE="$(grep -i '^MemTotal.*kB' /proc/meminfo | grep -o '[0-9]*')"
 	SWAPSIZE=$RAMSIZE
-	(printf "%s" "$SWAPSIZE" | grep -q '^[0-9][0-9]*$' && [ "$SWAPSIZE" -le 4194304 ]) || SWAPSIZE=4194304
+	# limit swap size to 4GB
+	if printf '%s' "$SWAPSIZE" | grep -q '^[0-9][0-9]*$' && [ "$SWAPSIZE" -le 4194304 ]; then
+		SWAPSIZE=4194304
+	fi
 	FREESPACE="$(df --output=avail --block-size=K "$SWAP_PATH" | grep -o '[0-9]*')"
 	if [ $FREESPACE -ge $SWAPSIZE ]; then
-		printf "Creating new swapfile: %s [%s kB] ...\n" "$SWAPFILE" "$SWAPSIZE"
+		printf 'Creating new swapfile: %s [%s kB] ...\n' "$SWAPFILE" "$SWAPSIZE"
 		dd if=/dev/zero of="$SWAPFILE" bs=1024 count=$SWAPSIZE
 		mkswap "$SWAPFILE"
 		chmod 0600 "$SWAPFILE"
 	else
-		printf "Error: swapfile cannot be created. Free space in %s is %s kB, required minimum is %s.\n" \
+		printf 'Error: swapfile cannot be created. Free= space in %s is %s kB, required minimum is %s.\n' \
 		"$SWAP_PATH" "$FREESPACE" "$SWAPSIZE"
 	fi
 fi
 
 # enable swapfile
 [ -f "$SWAPFILE" ] && swapon -v "$SWAPFILE"
-printf "\nSwap status:\n"
+printf '\nSwap status:\n'
 swapon --summary
diff --git a/etc/runit/ctrlaltdel b/etc/runit/ctrlaltdel
--- a/etc/runit/ctrlaltdel
+++ b/etc/runit/ctrlaltdel
@@ -6,11 +6,11 @@
 PATH=/usr/sbin:/usr/bin:/sbin:/bin
 
 # check root access
-if [ $(id -u) -ne 0 ]; then printf "Need to be root!\n"; exit 1; fi
+if [ $(id -u) -ne 0 ]; then printf 'Need to be root!\n'; exit 1; fi
 
 # check PID1
 if grep -vq runit /proc/1/cmdline; then
-	printf "ERROR: runit is not PID1, reboot failed.\n"
+	printf 'ERROR: runit is not PID1, reboot failed.\n'
 	exit 1
 fi
 
@@ -26,7 +26,7 @@ install --mode=0 /dev/null /run/runit.stopit
 install --mode=755 /dev/null /run/runit.reboot
 
 # print warning to all terminals
-printf "\n%s\n" "$MSG" | wall --nobanner
+printf '\n%s\n' "$MSG" | wall --nobanner
 
 # find runit-init binary
 RUNIT_INIT=$(grep -o 'init=[^ ]*' /proc/cmdline | grep -o '[^=]*$')
